class EleYemian:
    iframe_xuexiaoguanliyuan = (
    'xpath', "//iframe[contains(@src, 'https://ykf-webchat.7moor.com/view/moor_chat.html')]")
    iframe_yonghuzhuanguanliyuan = ()
    iframe_jueseguanli = ()
    iframe_caozuorizhi = ()
    iframe_denglurizhi = ()
    iframe_shouyeguanli = ()
    iframe_jueseguanli = ()

    qiehuanjuese = ('xpath', '//span[text()="切换角色"]')
    yunpingtaijuese = ('xpath', '//div[text()="云平台Py角色"]')
    queding1 = ('xpath', "/html/body/div[1]/div/div[2]/div[3]/div/div[3]/div/button[2]")
    guanliyuanyujuese = ('xpath', '//span[text()="管理员与角色"]')
    xuexiaoguanliyuan = ('xpath', '//span[text()="学校管理员"]')
    yonghuzhuanguanliyuan = ('xpath', '//span[text()="用户转管理员"]')
    jueseguanli = ('xpath', '//span[text()="角色管理"]')
    caozuorizhi = ('xpath', '//span[text()="操作日志"]')
    denglurizhi = ('xpath', '//span[text()="登录日志"]')
    shouyeguanli = ('xpath', '//span[text()="首页管理"]')

    dengluzhanghao = ('xpath', "//input[@placeholder='请输入登录账号']")
    zhanghaozhuangtai = ('xpath', "//input[@placeholder='账号状态']")
    chaxun = ('xpath', '//span[text()="查询"]')
    tianjiaguanliyuan = ('xpath', '//span[text()="添加管理员"]')
    shoujihao = ('xpath', "//input[@placeholder='登录账号，必填']")
    denglumima = ('xpath', "//input[@placeholder='登录密码(必填)']")
    danxuanjuese = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[2]/div['
                             '1]/form/div[3]/div[2]/div[2]/div/div[1]/label/span[1]/span')
    queding2 = ('xpath', "/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[4]/div/div[3]/span/button[2]/span")
    queding3 = ('xpath', "/html/body/div[8]/div[1]/button[2]/span")
    queding4 = ('xpath', "/html/body/div[9]/div[1]/button[2]/span")
    qingchu = ('xpath', '//span[text()="清除筛选条件"]')
    qiyong = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[2]/div[3]/table/tbody/tr[1]/td['
                       '6]/div/div/span')
    xiugaimima = ('xpath', "//span[@class='el-link--inner'][text()='修改密码']")
    xinmima = ('xpath', "//input[@placeholder='请输入密码']")
    querenmima = ('xpath', "//input[@placeholder='请输入确认密码']")
    xiugai = ('xpath', '//span[text()="修改"]')
    xianshimima = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[5]/div/div[2]/form/div['
                            '1]/div/div[1]/span/span/i')
    bianji = ('xpath', '//span[text()="编辑"]')
    xingming = ('xpath', "//input[@placeholder='姓名']")
    jiechusuoding = ('xpath', '//span[text()="解除锁定"]')
    shanchu = ('xpath', '//span[text()="删除"]')
    sheweiguanliyuan = ('xpath', '//span[text()="设为管理员"]')
    guanliyuan = ('xpath', '//div[text()="管理员"]')
    yonghu = ('xpath', '//div[text()="用户"]')
    qiyong2 = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[2]/div[3]/table/tbody/tr[1]/td['
                        '5]/div/div/span')
    danxuanjuese2 = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[2]/div['
                              '1]/form/div[2]/div[2]/div[2]/div/div[1]/label/span[1]/span')
    chexiaoguanli = ('xpath', '//span[text()="撤销管理"]')
    tianjiajuese = ('xpath', '//span[text()="添加角色"]')
    juesemingcheng = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[4]/div/div[2]/form/div[1]/div/div/input')
    caidanquanxuan = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[4]/div/div[2]/form/div[4]/div[2]/div[1]/div/div/div[1]/div/label/span/span')
    qiyong3 = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[2]/div[3]/table/tbody/tr[1]/td[3]/div/div/span')
    queding5 = ('xpath', '/html/body/div[7]/div[1]/button[2]')
    guanliyuanzhanghao = ('xpath', "//input[@placeholder='管理员账号']")
    caozuomokuai = ('xpath', "//input[@placeholder='操作模块']")
    kaishiriqi = ('xpath', "//input[@placeholder='开始日期']")
    jieshuriqi = ('xpath', "//input[@placeholder='结束日期']")
    mingandu = ('xpath', "//input[@placeholder='敏感度']")
    mokuaigongneng = ('xpath', "//input[@placeholder='模块功能']")
    tianjiayangshi = ('xpath', '//span[text()="添加学校首页样式"]')
    yangshimingcheng = ('xpath', "//input[@placeholder='样式名称']")
    tianjia = ('xpath', '/html/body/div[1]/div/main/div/div[2]/div[2]/div/div/div[4]/div/div[2]/form/div[2]/div/div/div[2]/div/div/div')
    gongneng1 = ('xpath', '/html/body/div[8]/div/div[2]/div/div[1]')
    gongneng11 = ('xpath', '/html/body/div[9]/div/div[2]/div/div[1]')
    qingkonggongneng = ('xpath', '//span[text()="清空首页功能"]')
    queding6 = ('xpath', '/html/body/div[8]/div/div[3]/span/button[2]')
    queding66 = ('xpath', '/html/body/div[9]/div/div[3]/span/button[2]/span')
    shurujuesemingcheng = ()
    qudaoshang = ()
    zhuangtai = ()
    jueseleixing = ()
